### ISSUE TITLE
Could not initialize class com.mxgraph.util.mxUtils

### ISSUE THREAD

**Issue by kitaekim077** [DanFaria/GOEnrichment#1]
Hi, Thank you for making a such useful tool.
However, I keep getting an error.

Could you check why this occurs?

2022-04-14 16:09:50 - Read 2260 genes
2022-04-14 16:09:50 - Running Fisher's exact test
2022-04-14 16:09:50 - Finished
2022-04-14 16:09:50 - Running multiple test correction
2022-04-14 16:09:50 - Finished
2022-04-14 16:09:50 - Saving result file 'MF_result.txt'
2022-04-14 16:09:50 - Finished
2022-04-14 16:09:50 - Saving graph file 'MF_graph'
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.mxgraph.util.mxUtils
	at com.mxgraph.view.mxGraph.postProcessCellStyle(Unknown Source)
	at com.mxgraph.view.mxGraph.getCellStyle(Unknown Source)
	at com.mxgraph.view.mxGraphView.createState(Unknown Source)
	at com.mxgraph.view.mxGraphView.getState(Unknown Source)
	at com.mxgraph.view.mxGraphView.validateCell(Unknown Source)
	at com.mxgraph.view.mxGraphView.validateCell(Unknown Source)
	at com.mxgraph.view.mxGraphView.validateCell(Unknown Source)
	at com.mxgraph.view.mxGraphView.validateCell(Unknown Source)
	at com.mxgraph.view.mxGraphView.validate(Unknown Source)
	at com.mxgraph.view.mxGraph.graphModelChanged(Unknown Source)
	at com.mxgraph.view.mxGraph$3.invoke(Unknown Source)
	at com.mxgraph.util.mxEventSource.fireEvent(Unknown Source)
	at com.mxgraph.util.mxEventSource.fireEvent(Unknown Source)
	at com.mxgraph.model.mxGraphModel$1.dispatch(Unknown Source)
	at com.mxgraph.model.mxGraphModel.endUpdate(Unknown Source)
	at graph.Graph.save(Graph.java:133)
	at main.GOEnrichment.saveGraph(GOEnrichment.java:270)
	at main.Main.main(Main.java:61)

**Comment by DanFaria** [comment]
Hi

I suspect that this could be a java version issue, but I need more input to figure out the source of the error:
-Did you get the compiled program from Releases? Or did you clone the repository and compile locally?
-With what java version are you running it?

Thanks,

Daniel

**Comment by DanFaria** [comment]
It seems that for some reason the jgraphx.jar was missing from the dependencies. I added it back, so the problem should be fixed now.
